<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="1" disabled="0" errors="0" time="0." timestamp="2025-09-27T20:58:41.876" name="AllTests">
  <testsuite name="TypeCheckerFunctionCallTest" tests="1" failures="1" disabled="0" skipped="0" errors="0" time="0." timestamp="2025-09-27T20:58:41.876">
    <testcase name="SmartPointerKindMismatch" file="tests/backend/test_type_checker.cpp" line="459" status="run" result="completed" time="0." timestamp="2025-09-27T20:58:41.876" classname="TypeCheckerFunctionCallTest">
      <failure message="tests/backend/test_type_checker.cpp:471&#x0A;Value of: result.isErr()&#x0A;  Actual: false&#x0A;Expected: true&#x0A;" type=""><![CDATA[tests/backend/test_type_checker.cpp:471
Value of: result.isErr()
  Actual: false
Expected: true
]]></failure>
      <failure message="unknown file&#x0A;C++ exception with description &quot;Called error() on ok Result&quot; thrown in the test body.&#x0A;" type=""><![CDATA[unknown file
C++ exception with description "Called error() on ok Result" thrown in the test body.
]]></failure>
    </testcase>
  </testsuite>
</testsuites>
